### PR TITLE
Import the version in the setup.py

### PR DESCRIPTION
**Pull request by lord63**
next time when we bump the version number, just edit the version num in the `leancloud/__init__.py`.

### CODE REVIEW

**Comment by aisk** [comment]
Hi @lord63 thank for PR, but the CI test failed seems like it imported the `leancloud` module before install, so the deps modules is not installed.

**Comment by lord63** [comment]
@aisk  Yeah, I'm trying to fix this problem.

**Comment by lord63** [comment]
@aisk Tests passed _(:3
I'll squash the commits into a single commit.

**Comment by aisk** [comment]
@lord63 I think it is weird to import another duplicate config(the modules deps) to avoid the version number duplicate.

I saw this SO page have a excellent way to avoid this (the top answer), can you use this method in this PR? thanks very much!

**Comment by lord63** [comment]
@aisk  Where is the SO page? _(:3
This one [What is the correct way to share package version with setup.py and the package?](http://stackoverflow.com/q/17583400/4890577)

**Comment by aisk** [comment]
@lord63 sorry 😂, this one: http://stackoverflow.com/questions/17583443/what-is-the-correct-way-to-share-package-version-with-setup-py-and-the-package

**Comment by lord63** [comment]
> I think it is weird to import another duplicate config(the modules deps) to avoid the version number duplicate.

By the way, I'm curious why this behavior seems weird?

---

The [Python Packaging User Guide - Single-sourcing the Project Version](https://packaging.python.org/en/latest/single_source_version) lists several ways to maintain a single source of truth for the version number of your project, Including my way and your suggested way.

why I choose the import way:

- simple
- import error is not a big problem for the project, since we install the package via setup.py's `install_required`. Running tests and doing some development is usually for developers, a note for them should be enough(e.g. how to run the tests), 
- I usually specify the requirements in the text file, and we can pin the versions. Also, we can split the dependencies to dev-requirements.txt, requirements.txt, prod-requirements.txt and etc.

**Comment by aisk** [comment]
@lord63 I think we solved the "maintenance one version number in two files" problem by introduced "maintenance one module deps in two files". Now I think's not a big problem because the deps is not updated frequently than the version number 😅

But if there is a better solution, like using the 'pkg_resources', I think it's better to use it.

**Comment by lord63** [comment]
> But if there is a better solution, like using the 'pkg_resources', I think it's better to use it.

Hmmm, could you please explain why this technique is much better? It's totally OK for me to change to use it , just curious why it's better. And you need install the package first before fetching the version number. I'm can't be convinced to change it.

Also, manage the deps in a text file is still a good way, you may need some packages when developing, e.g. `nose` in your case(although it is preinstalled in travis).

By the way, just found [httpie](https://github.com/jkbrzt/httpie), [ansible](https://github.com/ansible/ansible) are using the import way; flask, requests are using the reading the file and using regex to parse the version, and finally the [sentry](https://github.com/getsentry/sentry/blob/master/src/sentry/__init__.py) are using the way you suggested.

Oh, if you think this patch is not necessary and the original way is fine, it's OK to close the PR, I should open a issue to discuss it before :-/

**Comment by aisk** [comment]
The only difference is, we should manage the deps in two place, one is `setup.py`, another is `requirements.txt`.

**Comment by lord63** [comment]
In my opinion, deps in `setup.py` is for users, while deps in `requirements.txt` is for developers, they are not the same. 
Take [my project](https://github.com/lord63/tldr.py) as an example, the package just need `click` and `PyYAML` when install, so specify them in the [`setup.py`](https://github.com/lord63/tldr.py/blob/master/setup.py), when developing and running the tests, you need `pytest`, `pytest-pep8`, `mock` and `tox`, so specify them in the `requirements.txt`. Sometimes, you need pin the package version , I use [pip-tools](https://github.com/nvie/pip-tools) to do it, for example: [mei-api's requirements](https://github.com/lord63/me-api/tree/master/requirements)

**Comment by aisk** [comment]
@lord63 ok, I agree with you, thanks for PR!

**Pull request merged**
