### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by lord63**
This PR is related to #43.
Note that only tests are fine and we still need carefully review on it before merge it to master.
Let me know if you have any concerns.

### CODE REVIEW

**Comment by lord63** [comment]
@aisk  CI failed _(:3JZ 
The weird problem is, the master branch is fine while the python3 branch you push failed(They are the same, right?). And my PR has the same problem. I remember the tests are fine when I run it on my computer.

**Comment by aisk** [comment]
@lord63 Hi, I saw you included a flask compat file in this PR, I'm wondering why just keep using six module ?

**Comment by lord63** [comment]
@aisk 
1. we don't have to depend on the six module, and there is no need for us to depend on it;
2. much more flexible, add the compatible functions as we want;
3. the code seems a bit ugly when using the six module in my opinion _(:3JZ

Ah, at first it was just an attempt to port the code, so I did it as I want. And finally it seems OK, so send you the PR. I should ask your preference before. Orz

**Comment by lord63** [comment]
@aisk  By the way, could you please take a look at the failing test?

* the master branch: [travis is ok](https://travis-ci.org/leancloud/python-sdk/builds/114151201)
* the python3 branch: [travis failed](https://travis-ci.org/leancloud/python-sdk/builds/116669067)
* my PR: [travis failed](https://travis-ci.org/leancloud/python-sdk/builds/116797632)

the first and the second are the same, but the second failed, with the same error with my PR.

**Comment by aisk** [comment]
@lord63 I think the CI check failed is because our test cases is not "threading safe", and travis runs the test in same time. So can you change the app id pairs in python3 test codes to this:

- app id: 8FfQwpvihLHK4htqmtEvkNrv
- app key: eE9tNOcCiWoMHM1phxY41rAz
- master key: 75zAjEJSj7lifKQqKSTryae9

**Comment by lord63** [comment]
@aisk  But have you notice that your original python3 branch(same HEAD with master also failed, and there is only python2, you can take a look at [here](https://travis-ci.org/leancloud/python-sdk/builds/116669067))

**Comment by lord63** [comment]
You can run the tests `$ nosetests tests/test_push.py` at the master branch on your computer, it also failed.

**Comment by aisk** [comment]
Got it, now it's failed even the master branch, I'll resolve it as soon as I can.

**Comment by hjiang** [comment]
@lord63 回复你邮件的时候被退回了，没有其他联系方式，所以在这里告诉你一下。
~~~
Delivery to the following recipient failed permanently:

     me@lord63.com

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for the recipient domain lord63.com by mx4.name.com. [173.192.7.99].

The error that the other server returned was:
554 5.1.1 <me@lord63.com>: Recipient address rejected: User unknown
~~~

**Comment by lord63** [comment]
@hjiang  lord63.j@gmail.com  囧rz

**Comment by aisk** [comment]
@lord63 the travis CI seems passed :+1: , but could you please squash the commits into a single commit? I'll merge it then.

**Comment by lord63** [comment]
@aisk I usually prefer small commits with detailed info in the commit message, it notes the reason why you do the change and the related things. Squash all the commits into a single one will lose all the information. In this case, In my opinion, I think there is no need to squash the commits.

Sometimes when you do a temp commit, you should squash the commits so that the commit has all the related contents and make the history clean.

It's recommended to keep the commits to have the commit log history, since there are 23 files changed, nearly 350 lines changed. And I also take care of the commit messages with reasons and changes.

>
Finally, VCSes give you the capability to annotate your data, attaching explanatory comments about the intention behind each change to it and a record of who was responsible for each change. Even for a programmer working solo, change histories are an important aid to memory; for a multi-person project they become a vitally important form of communication among developers.


Any ideas?

**Comment by aisk** [comment]
@lord63 I think it's better to have keep a single commit when the whole changes was just doing one thing, and it's better to review and revert in this way.

**Comment by lord63** [comment]
@aisk 
> it's better to revert

In my opinion, NO. If I squash all the commits into a single commit, revert the commit will discard all the changes. If keep the history:

* revert the merge branch: `git revert -m 1 merge_commit_sha`
* revert a single commit: `git revert commit_sha`

You have much more control in this case since you can choose to revert all the changes or just one commit change.

> it's better to review

review on github and you can still see all the changes.

---

I know that sometimes you should squash the commits, for example, you commit some changes, and then the collaborator ask you do some changes, then you push several commit to fix the problem, in this case, it's better to squash the temporary commits for a clean history.

But squash the commits doesn't have any benefits in this case, but if you insist that, I will.

**Comment by lord63** [comment]
@aisk  Please hold on for a while before merging the code into master, just leave it on the python3 branch, I'll check the test coverage. If the coverage is too low, there may be some potential bugs.

**Comment by aisk** [comment]
@lord63 no problem.

**Comment by adamin1990** [comment]
i am using python 3.4.3,and when i input these code ,it print these errors`AttributeError: 'dict' object has no attribute 'iteritems'`
`import leancloud
from leancloud import Object
from leancloud import LeanCloudError
leancloud.init("","")
TestObject= Object.extend('TestObject')
test_object = TestObject()
test_object.set('foo', 'bar')
try:
    test_object.save()
except LeanCloudError:
    print("出错了")`

**Comment by lord63** [comment]
@adamin1990 Hi, are you using the latest python3 branch on github? Because the latest version for leancloud python SDK hasn't added the python3 support.

**Pull request merged**
