### PR TITLE
Remove the hack for python 2.6

### PR DESCRIPTION
**Pull request by lord63**
since we dropped the support for 2.6 in the PR #137

### CODE REVIEW

**Comment by aisk** [comment]
Sorry, I saw the tests in travis is still use the CN API Server, so it's hard to pass the tests in travis. I'm trying fix this now.

**Comment by aisk** [comment]
@lord63 can you merge the master to your PR, I had made some changes to let travis run the tests in leancloud US Server.

**Comment by lord63** [comment]
@aisk Failed, don't know why _(:3

**Comment by aisk** [comment]
seems like you have missed the `test_engine.py` changes when merge codes from master.

**Comment by lord63** [comment]
@aisk Could you please try to run the tests on your computer, is the test OK? Seems OK for me.

**Comment by lord63** [comment]
@aisk  I guess the problem is not the `test_engine.py`, the conflict is because the master branch and the master branch are different, so we just keep the changes in python3 branch.

**Comment by aisk** [comment]
Same error on my machine.

**Comment by lord63** [comment]
@aisk still can't reproduce the problem _(:3

**Comment by aisk** [comment]
@lord63 I think you are using the default APP ID / key with CN API Server, can you test it with the APP ID/ key in the travis config? (exports the envs in it)

**Comment by lord63** [comment]
@aisk  QAQ can reproduce the problem... Any ideas that how to fix it?

**Comment by aisk** [comment]
already fixed in master: https://github.com/leancloud/python-sdk/blob/master/tests/test_engine.py#L346

**Comment by lord63** [comment]
Wait a moment, the merge still has a problem. I'll Update the comment.   囧rz

**Pull request merged**
