### PR TITLE
fix: fix push test failed bug

### PR DESCRIPTION
**Pull request by aisk**

### CODE REVIEW

**Comment by aisk** [comment]
@lord63 Looks like the server's logic is changed

**Comment by lord63** [comment]
@aisk  The weired thing is the master seems OK again. Could please test the master branch on your computer?

**Comment by aisk** [comment]
@lord63 the master branch failed in the same way

**Comment by lord63** [comment]
@aisk could you please try to restart the test on my PR on travis, just click the circle button on the [page](https://travis-ci.org/leancloud/python-sdk/builds/116797632) by the right side.

**Comment by lord63** [comment]
@aisk The weird thing  is that the tests on my PR for 2.x is ok AGAIN!  <https://travis-ci.org/leancloud/python-sdk/jobs/116797633>   _(:3JZ

**Comment by aisk** [comment]
I think it's because in this PR's tests, there was already a record in `_Installation` class, so #161 can pass the unit tests.

**Pull request merged**
